use std.system.exit;

func assert_eq[T](a: T, b: T) {
    if a != b {
        print("assertion failed: ");
        print(a);
        print(" != ");
        println(b);
        exit(1);
    }
}

func assert_ne[T](a: T, b: T) {
    if a == b {
        print("assertion failed: ");
        print(a);
        print(" == ");
        println(b);
        exit(1);
    }
}

func fail() {
	print("test failed");
}
