#! output: success: 583; failure: ACCESS_DENIED; failure: NOT_FOUND; failure: NOT_FOUND

enum Error {
    NOT_FOUND,
    ACCESS_DENIED,
}

func load_value(id: u32) -> i64 except Error {
    if id == 0 { return 583; }
    else if id == 1 { return Error.ACCESS_DENIED; }
    else { return Error.NOT_FOUND; }
}

func print_value(id: u32) {
    try value in load_value(id) {
        print("success: ");
        print(value);
    } except error: Error {
        print("failure: ");
        print(error);
    }
}

func main() {
    print_value(0);
    print("; ");
    print_value(1);
    print("; ");
    print_value(2);
    print("; ");
    print_value(593);
}