#! output: success: 583; failure: ACCESS_DENIED; failure: NOT_FOUND; failure: NOT_FOUND;

enum Error {
    NOT_FOUND,
    ACCESS_DENIED,
}

func load_value(id: u32) -> i64 except Error {
    if id == 0 { return 583; }
    else if id == 1 { return Error.ACCESS_DENIED; }
    else { return Error.NOT_FOUND; }
}

func load_and_print(id: u32) {
    try value in load_value(id) {
        print("success: ");
        print(value);
    } except error: Error {
        print("failure: ");
        print(error);
    }

    print("; ");
}

func main() {
    load_and_print(0);
    load_and_print(1);
    load_and_print(2);
    load_and_print(593);
}